/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package xgame.othrones;

import javafx.scene.input.MouseEvent;

/**
 *
 * @author Mabweh
 */
public class gameMenu extends javax.swing.JFrame {

    /**
     * Creates new form gameMenu
     */
    public gameMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        help = new javax.swing.JButton();
        about = new javax.swing.JButton();
        credit = new javax.swing.JButton();
        exitt = new javax.swing.JButton();
        play = new javax.swing.JButton();
        musicButton = new javax.swing.JToggleButton();
        backImage = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("xGame oThrones");
        setName("xGameoThrones"); // NOI18N
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowDeactivated(java.awt.event.WindowEvent evt) {
                formWindowDeactivated(evt);
            }
        });
        getContentPane().setLayout(null);

        help.setText("HELP");
        help.setName("help"); // NOI18N
        help.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                helpActionPerformed(evt);
            }
        });
        getContentPane().add(help);
        help.setBounds(243, 150, 160, 40);

        about.setText("ABOUT");
        about.setName("about"); // NOI18N
        about.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aboutActionPerformed(evt);
            }
        });
        getContentPane().add(about);
        about.setBounds(463, 150, 160, 40);

        credit.setText("CREDIT");
        credit.setName("credit"); // NOI18N
        credit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                creditActionPerformed(evt);
            }
        });
        getContentPane().add(credit);
        credit.setBounds(673, 148, 170, 40);

        exitt.setText("EXIT");
        exitt.setName("exitt"); // NOI18N
        exitt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exittActionPerformed(evt);
            }
        });
        getContentPane().add(exitt);
        exitt.setBounds(883, 150, 170, 40);

        play.setText("PLAY");
        play.setName("play"); // NOI18N
        play.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                playActionPerformed(evt);
            }
        });
        getContentPane().add(play);
        play.setBounds(40, 150, 160, 40);

        musicButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/xgame/othrones/musicButtonPlay.png"))); // NOI18N
        musicButton.setToolTipText("turrn on/off music");
        musicButton.setBorderPainted(false);
        musicButton.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        musicButton.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/xgame/othrones/musicButtonPause.png"))); // NOI18N
        musicButton.setDisabledSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/xgame/othrones/musicButtonPause.png"))); // NOI18N
        musicButton.setName("musicButton"); // NOI18N
        musicButton.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/xgame/othrones/musicButtonPause.png"))); // NOI18N
        musicButton.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/xgame/othrones/musicButtonPlay.png"))); // NOI18N
        musicButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                musicButtonMouseClicked(evt);
            }
        });
        getContentPane().add(musicButton);
        musicButton.setBounds(70, 490, 100, 80);

        backImage.setFont(new java.awt.Font("Charlemagne Std", 1, 10)); // NOI18N
        backImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/xgame/othrones/gameBackground.png"))); // NOI18N
        backImage.setText("jLabel1");
        backImage.setToolTipText("");
        backImage.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        backImage.setName("backImage"); // NOI18N
        backImage.setOpaque(true);
        getContentPane().add(backImage);
        backImage.setBounds(0, 0, 1070, 620);
        backImage.getAccessibleContext().setAccessibleName("backImage");

        jButton1.setText("jButton1");
        jButton1.setName("jButton1"); // NOI18N
        getContentPane().add(jButton1);
        jButton1.setBounds(290, 490, 73, 28);

        setSize(new java.awt.Dimension(1085, 650));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    
   
    
    private void musicButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_musicButtonMouseClicked
        // TODO add your handling code here:
      musicButton.setEnabled(true);
      
      
    }//GEN-LAST:event_musicButtonMouseClicked

    
    
    private void playActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_playActionPerformed
        // TODO add your handling code here:
        
        //TicTacToeV1 ticTacToeV1 = new TicTacToeV1();
        new TicTacToeV1();
        
    }//GEN-LAST:event_playActionPerformed

    private void aboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aboutActionPerformed
        // TODO add your handling code here:
        gameAbout gameAbout = new gameAbout();
    }//GEN-LAST:event_aboutActionPerformed

    private void creditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_creditActionPerformed
        // TODO add your handling code here:
        gameCredit gameCredit = new gameCredit();
    }//GEN-LAST:event_creditActionPerformed

    private void exittActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exittActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_exittActionPerformed

    private void helpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_helpActionPerformed
        // TODO add your handling code here:
        gameHelp gameHelp = new gameHelp();
    }//GEN-LAST:event_helpActionPerformed

    private void formWindowDeactivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowDeactivated
        // TODO add your handling code here:
        
    }//GEN-LAST:event_formWindowDeactivated

    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String[] args) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(gameMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(gameMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(gameMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(gameMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new gameMenu().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton about;
    public javax.swing.JLabel backImage;
    public javax.swing.JButton credit;
    public javax.swing.JButton exitt;
    public javax.swing.JButton help;
    public javax.swing.JButton jButton1;
    public javax.swing.JToggleButton musicButton;
    public javax.swing.JButton play;
    // End of variables declaration//GEN-END:variables
}
